#ifndef COMMANDS_H
#define COMMANDS_H

enum {
	//Client
	CMD_NEWGAME, // <Data>
	CMD_RELEASE, //NO <Void>
	CMD_GAMELIST, // <Mode>
	CMD_MODELIST, // <Void>
	CMD_GETMODE, // <Name>
	CMD_REGISTER, //NO <Data>
	CMD_LOGIN, //NO <Data>
	//Server
	CMD_GAMEDATA, // <Data>
	CMD_MODEDATA, // <Data>
	CMD_MODETRANSFER, // <Size, Mode>
	CMD_MODEPART, // <datablock>
	CMD_MODEFINISH, // <Void>
	CMD_REGLOGANSW // <status>
};

enum {
	ERR_LOST_CONNECTION,
	CMD_NONE,
	CMD_SECURITY_MODE,
	CMD_UNDEFENDED_MODE,
	CMD_NEWKEYS,
	CMD_MENTAL_KEY, // for Pk
	CMD_CONFIRM_OF_READY, // for check
	CMD_LOGCONTROL, // log
	CMD_DECODECONTROL, // decode
	CMD_SEND_IDX_MODEL,
	CMD_SEND_IDX_REAL,
	CMD_SEND_IDX_ONHAND,
	CMD_ON_HAND_UPDATE,
	CMD_ON_HAND_SECRET,
	CMD_ON_HAND_OPEN,
	CMD_MENTAL_BACK, // answer
	CMD_GET_LOG, // for log transfer
	CMD_END_LOG, // for log transfer
	CMD_PASS_CARD_PHYS,
	CMD_PASS_CARD_VIS,
	CMD_SEND_MSG,
	CMD_CONNECT,
	CMD_HELLO,
	CMD_READY,
	CMD_CHECK,
	CMD_OK,
	CMD_CANCEL,
	CMD_ERROR,
	CMD_NOOP,
	CMD_STEP_YOUR_ID,
	CMD_STEP_I,
	CMD_STEP_NOW,
	CMD_STEP_FINISH,
	CMD_ADDTOPLAYER,
	CMD_REMFROMPLAYER,
	CMD_ADDTOGROUP,
	CMD_REMFROMGROUP
};

#endif
