#ifndef API_LIST_HPP
#define API_LIST_HPP

#define BUFFER_SIZE 1024

enum {
	REG_OK,
	REG_FAIL,
	LOG_OK,
	LOG_FAIL
};

enum {
	INIT_GAMEPROC,
	INIT_ASKER
};

struct RegData {
	char nick[16];
	char fname[16];
	char sname[20];
	char hash[32];
};

struct GameData {
	char title[30];
	char mode[30];
	unsigned short port;
	unsigned int ip;
};

struct GameDataItem {
	GameData data;
	int idx;
	GameDataItem *next;
};

struct ModeData {
	char title[30];
	char fname[30];
};

struct ModeDataItem {
	ModeData data;
	ModeDataItem *next;
};

enum {
	//Asker
	API_GAMELISTITEM,
	API_MODELISTITEM,
	API_MODEDOWNLOAD,
	API_ANSWER,
	//Back
	API_NEWPLAYER,
	API_NEWCHATLINE,
	API_READYCHECK,
	API_ADDCARDSONHAND,
	API_ADDSECRETCARDSONHAND,
	API_OPENCARDSONHAND,
	API_CREATEBUTTON,
	API_SETBUTTONTEXT,
	API_SETBUTTONENABLED,
	API_DROPBUTTON, 
	API_CREATECARDSGROUP,
	API_SETCARDSGROUPTEXT,
	API_SETCARDSGROUPXY,
	API_SETCARDSGROUPVERTICAL,
	API_SETCARDSGROUPCONTROL,
	API_SETCARDSGROUPENABLED,
	API_DROPCARDSGROUP,
	API_SETPLAYERCARDSXY,
	API_SETPLAYERCARDSVERTICAL,
	API_SETPLAYERCARDSCONTROL,
	API_SETPLAYERCARDSENABLED,
	API_SIZESELPLAYERCARDS,
	API_GETSELPLAYERCARDS,
	API_SIZEALLPLAYERCARDS, //TO CORE!
	API_GETALLPLAYERCARDS, //TO CORE!
	API_OPENPLAYERCARDS,
	API_ADDTOPLAYERCARDS,
	API_REMFROMPLAYERCARDS,
	API_SIZESELCARDSGROUP,
	API_GETSELCARDSGROUP,
	API_SIZEALLCARDSGROUP, //TO CORE!
	API_GETALLCARDSGROUP, //TO CORE!
	API_ADDTOCARDSGROUP,
	API_REMFROMCARDSGROUP,
	API_SETPLAYERSCORE,
	//
	API_DOWNCOUNTLOG, //NO
	API_INITLOG //NO
};

#endif
